version: "3"
services:
  tsoha:
    image: roeoeri/tsoha
    ports:
      - 80:5000
    container_name: tsoha
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
